import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, symlink, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { buildApp } from '../src/app.js';
import { configFromEnv } from '../src/config.js';
import { fragmentType } from '../src/page-fragment.js';

test('HTTP fragments pin plugin JS/CSS and templates to a version across requests and engine restarts', async t => {
  const root = await mkdtemp(join(tmpdir(), 'karui-plugin-http-'));
  const pluginDir = join(root, 'plugins/sample');
  await mkdir(join(pluginDir, 'assets/nested'), { recursive: true }); await mkdir(join(root, 'pages'));
  await writeFile(join(root, 'site.yml'), 'title: Test\nhome: /\nlanguage: en\nlanguages: [en, pl]\nmenu: []\n');
  await writeFile(join(root, 'pages/sample.md'), '---\ntitle: Sample\nplugin: sample\n---\n');
  const source = 'import { resourceLimits } from "node:worker_threads"; export default context => context.suffix === "/limits" ? {type:"json",data:resourceLimits} : context.suffix === "/language" ? {type:"json",data:{language:context.language,defaultLanguage:context.defaultLanguage}} : ({type:"view",template:"view.edge",client:"client.ts",styles:"style.css",data:{href:context.page.href}})';
  await writeFile(join(pluginDir, 'index.ts'), source);
  await writeFile(join(pluginDir, 'client.ts'), 'postMessage("version-one")');
  await writeFile(join(pluginDir, 'style.css'), '.version-one { background: url("./assets/icon.txt") }');
  await writeFile(join(pluginDir, 'view.edge'), '@include("partial")\n<p>{{ href }}</p><img src="{{ pluginAssets[\'icon.txt\'] }}">');
  await writeFile(join(pluginDir, 'partial.edge'), '<b>version-one</b>');
  await writeFile(join(pluginDir, 'assets/icon.txt'), 'asset-version-one');
  await writeFile(join(pluginDir, 'assets/nested/data.bin'), Buffer.from([0, 1, 2, 3]));
  await writeFile(join(pluginDir, 'assets/.hidden.txt'), 'not-public');
  await writeFile(join(root, 'outside.txt'), 'outside-plugin');
  await symlink(join(root, 'outside.txt'), join(pluginDir, 'assets/leak.txt'));
  await writeFile(join(pluginDir, 'plugin.json'), '{"version":"1"}');
  const config = { ...configFromEnv({ PLUGIN_WORKER_OLD_GENERATION_MB: '96', PLUGIN_WORKER_YOUNG_GENERATION_MB: '24', PLUGIN_WORKER_STACK_MB: '6' }), contentDir: root, contentCacheDir: join(root, 'cache'), pluginWorkers: 1, pluginMaxWorkers: 2 };
  let app = await buildApp(config);
  t.after(async () => { await app.close(); await rm(root, { recursive: true, force: true }); });
  const get = () => app.inject({ url: '/sample', headers: { accept: fragmentType } });
  const first = await get(); assert.equal(first.statusCode, 200, first.body);
  const limits = (await app.inject('/sample/limits')).json();
  for (const [key, value] of Object.entries(config.pluginMemoryLimits)) assert.equal(limits[key], value, key);
  assert.deepEqual((await app.inject('/sample/language?lang=pl')).json(), { language: 'pl', defaultLanguage: 'en' });
  const data = first.json(); assert.match(data.content, /version-one/); assert.match(data.content, /\/sample/);
  const clientURL = /data-script="([^"]+)"/.exec(data.content)![1]!;
  assert.match(clientURL, /client\.ts\?v=[a-f0-9]{64}$/);
  const client = await app.inject(clientURL);
  assert.equal(client.statusCode, 200); assert.match(client.body, /version-one/); assert.match(client.headers['cache-control']!, /immutable/);
  const key = /\?v=([a-f0-9]{64})$/.exec(clientURL)![1]!;
  const assetURL = /<img src="([^"]+)"/.exec(data.content)![1]!;
  assert.equal(assetURL, `/plugin-assets/sample/assets/${key}/icon.txt`);
  const asset = await app.inject(assetURL);
  assert.equal(asset.statusCode, 200); assert.equal(asset.body, 'asset-version-one'); assert.match(asset.headers['cache-control']!, /immutable/);
  const firstStyle = await app.inject(data.styles[0]);
  assert.equal(firstStyle.body, `.version-one { background: url("./assets/${key}/icon.txt") }`);
  assert.equal((await app.inject(`/plugin-assets/sample/assets/${key}/nested/data.bin`)).rawPayload.toString('hex'), '00010203');
  assert.equal((await app.inject(`/plugin-assets/sample/assets/${key}/index.ts`)).statusCode, 404);
  assert.equal((await app.inject(`/plugin-assets/sample/assets/${key}/.hidden.txt`)).statusCode, 404);
  assert.equal((await app.inject(`/plugin-assets/sample/assets/${key}/leak.txt`)).statusCode, 404);
  // Source edits alone must not trigger compilation, even after restarting the engine.
  await writeFile(join(pluginDir, 'index.ts'), '@invalid typescript');
  await writeFile(join(pluginDir, 'partial.edge'), '<b>version-two</b>');
  await writeFile(join(pluginDir, 'assets/icon.txt'), 'asset-version-two');
  assert.match((await get()).body, /version-one/);
  await app.close(); app = await buildApp(config);
  assert.match((await get()).body, /version-one/);
  await writeFile(join(pluginDir, 'index.ts'), source);
  await writeFile(join(pluginDir, 'client.ts'), 'postMessage("version-two")');
  await writeFile(join(pluginDir, 'plugin.json'), '{"version":"2"}');
  const changed = await get(); assert.equal(changed.statusCode, 200, changed.body);
  assert.match(changed.body, /version-two/); assert.notEqual(changed.json().styles[0], data.styles[0]);
  const newURL = /data-script="([^"]+)"/.exec(changed.json().content)![1]!;
  const newAssetURL = /<img src="([^"]+)"/.exec(changed.json().content)![1]!;
  assert.match((await app.inject(newURL)).body, /version-two/);
  assert.equal((await app.inject(newAssetURL)).body, 'asset-version-two');
  assert.match((await app.inject(clientURL)).body, /version-one/, 'An already opened document can finish loading its pinned assets');
  assert.equal((await app.inject(assetURL)).body, 'asset-version-one', 'An already opened document retains its pinned static assets');
  assert.equal((await app.inject('/plugin-assets/sample/client.ts?v=invalid')).statusCode, 404);
  assert.equal((await app.inject('/plugin-assets/sample/plugin.json')).statusCode, 404);
});
